apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
  name: nginx
  namespace: dev
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    deployment: nginx
  type: ClusterIP
