apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-update
  namespace: openshift-gitops
spec:
  schedule: "00 00 12 12 *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: openshift-gitops-argocd-application-controller
          containers:
          - name: update
            image:  image-registry.openshift-image-registry.svc:5000/openshift/cli
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - date; oc adm upgrade --to-latest=true
          restartPolicy: OnFailure
