apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-update
  namespace: admin
spec:
  schedule: "36 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cluster-update
          containers:
          - name: update
            image:  openshift/cli
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - date; oc adm upgrade --to-latest=true
          restartPolicy: OnFailure
