apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks-vdb"
  namespace: "openshift-local-storage" 
spec:
  nodeSelector: 
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker0.ocp4.local.net
          - worker1.ocp4.local.net
          - worker2.ocp4.local.net
  storageClassDevices:
    - storageClassName: "local-vdb" 
      volumeMode: Filesystem  
      devicePaths: 
        - /dev/vdb

