---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: cluster-update
    namespace: admin

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-update
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - update
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-update
subjects:
- kind: ServiceAccount
  name: cluster-update
  namespace: admin
roleRef:
   kind: ClusterRole
   name: cluster-update
   apiGroup: ""
